#!/bin/zsh
# 🎯 START HERE - Complete Terminal Guide

echo "========================================"
echo "🚀 How to Start the URL Scraper"
echo "========================================"
echo ""
echo "📍 STEP 1: Open Terminal"
echo "   - Press Cmd + Space"
echo "   - Type 'Terminal'"
echo "   - Press Enter"
echo ""
echo "📍 STEP 2: Navigate to project folder"
echo "   Copy and paste this:"
echo ""
echo "   cd /Users/thelegendofzjui/Documents/GitHub/url_scraper_agent.py"
echo ""
echo "📍 STEP 3: Run the scraper"
echo "   Choose one of these commands:"
echo ""
echo "   # Option A: Quick test (mock AI, no blockchain)"
echo "   python3 serve_frontend.py --url 'https://techcrunch.com' --ai-mock"
echo ""
echo "   # Option B: Full scrape with blockchain"
echo "   python3 serve_frontend.py --url 'https://techcrunch.com' --create-market --enable-blockchain"
echo ""
echo "========================================"
echo "✅ That's it! The scraper will run and show you the results."
echo ""
